[Arduino]
# Портът за връзка (напр. COM3 за Windows или /dev/ttyUSB0 за Linux/Mac)
Port = COM24
# Скорост на комуникация (трябва да съвпада със Serial.begin в C++ кода)
BaudRate = 9600

[API]
# Адрес на Django сървъра (без http://)
Host = 127.0.0.1
# Порт на Django сървъра
Port = 8000
# Път до endpoint-а за сканиране
Endpoint = /api/scan/