# Generated by Django 4.2.18 on 2026-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='UID на картата')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Притежател')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на регистрация')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карти',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unknown_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Време на събитието')),
                ('event_type', models.CharField(choices=[('GRANTED', 'Достъпът е разрешен'), ('DENIED_INACTIVE', 'Отказан достъп (Блокирана карта)'), ('DENIED_UNKNOWN', 'Отказан достъп (Непозната карта)')], max_length=20, verbose_name='Резултат')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.card')),
            ],
            options={
                'verbose_name': 'Лог на достъп',
                'verbose_name_plural': 'Логове на достъп',
                'ordering': ['-timestamp'],
            },
        ),
    ]
